### ISSUE TITLE
please provide example how to encode opus from ffmpeg pipe

### ISSUE THREAD

**Issue by kinoher** [mccoyst/ogg#6]
i have ffmpeg transcode stdout 
```	
cmd:=exec.Command("ffmpeg","-re", "-i","http://ice912.echo.msk.ru:9120/stream", "-acodec","libopus","-ab","32k", "-ar","48000","-f","s16le","pipe:1")
	serr, efdd := cmd.StderrPipe()
	stdp, perr := cmd.StdoutPipe()
	fmt.Println("ffmpeg start")
	//cmder:=cmd.Run()
	cmder := cmd.Start()
	time.Sleep(250 * time.Millisecond)
	fmt.Printf("ffmpeg start %+v", cmd.ProcessState)
	//o,e:=cmd.CombinedOutput()
	//fmt.Printf("ffmpeg stop,%s,,err %s\n",o,e)
	f, f_err := os.OpenFile("/home/kino/opustest2.ogg", os.O_CREATE|os.O_RDWR, os.ModePerm)
	if f_err != nil {
		return f_err
	}
	fibd := bufio.NewWriter(f)
	buffer := bufio.NewReader(stdp)
	fmt.Printf("buf init buffered %s", buffer.Buffered())
	if perr != nil {
		fmt.Printf("process create err %s,", perr)
		return perr
	}
	if cmder != nil {
		return cmder
	}

	// Sleep for a specified amount of time before playing the sound
	time.Sleep(250 * time.Millisecond)
```
and i can't understud how incopsulate opus in ogg.
please help me

**Comment by mccoyst** [comment]
I'm sorry to say that I don't know what that command does. The general way to use this library is to take whole packets produced by an audio encoder and pass them into the Encode functions. For example:

```
defer w.Close()
e := ogg.NewEncoder(1, w)
// This is just an example; there are lots of ways to get a packet
granule, packet := someAudioEncoder.FirstPacket()
err := e.EncodeBOS(granule, packet)
…
for ; packet != nil; granule, packet = someAudioEncoder.NextPacket() {
    err = e.Encode(granule, packet)
    …
}
e.EncodeEOS()
```

Basically, you will need to determine what that command is outputting in order to delimit the packets. If it is outputting opus, it is likely already encapsulated in ogg.

**Comment by kinoher** [comment]
please read this  [RFC](https://tools.ietf.org/html/rfc7845.html) this command get mp3 and output   PCM signed 16-bit little-endian
 i try this [code](https://gist.github.com/kinoher/b72a21310a081d7030e9371c3519a5a8) but something wrong

**Comment by mccoyst** [comment]
That code is hard to read and I cannot debug it for you. However, I did notice that it is reading into a buffer of size `oggmxpg:=512`, which is not the maximum size for an ogg page. It is also not the maximum size of an opus packet, which is even larger. You are then simply encoding each of these 512 bytes into separate ogg pages, which you can see in the RFC is not valid for several reasons. Also, you are always passing in `1` for the granule position — this is another thing that has to be updated per page as described in the RFC.
